package.json, server/config.ts
Some requests, expecially while API cache is not warm, can take a bit long
so we're increasing the timeouts to try and reduce/avoid them.
=> Increased Incentives API timeouts to 60s

helm_deploy/hmpps-incentives-ui/values.yaml, package-lock.json
Similarly to what already done in the Incentives API [here](https://github.com/ministryofjustice/hmpps-incentives-api/pull/15/files#diff-5ef4f2b0d47cd40c718eb93fc47bb057e8d41c41ae435aa4214f852ce1199282R17-R20) but on the UI side of the fence.
(Also bumped patch version of typescript.)
=> INC-149: Increased nginx timeouts to 2m (conservative)

integration_tests/integration/incentivesTable.spec.ts, integration_tests/pages/behaviourEntriesPage.ts, server/routes/index.test.ts, server/views/pages/incentives-table.njk
- Prisoner name links to DPS 'case notes' tab (and with `fromDate` set to 3 months ago)
- links to DPS Incentive Level Details don't filter by level
- Adjudications links don't have the `fromDate` filter (as this is likely to not show proven adjudications because the date they were recorded is older than 3 months)
Also, showing Prisoner Number below their last name/first name as in prototype(s).
=> INC-167: Tweaks to behaviour entries table's links

assets/js/govukFrontendInit.js, feature.env, package-lock.json, server/views/pages/incentives-table.njk, server/views/partials/layout.njk
Using MoJ's [Sortable table component](https://design-patterns.service.justice.gov.uk/components/sortable-table/).
Also:
- https://github.com/ministryofjustice/hmpps-incentives-ui/commit/fc1db303a1b45a917ba873a9ddcd6783456bf269 bumped `govuk-frontend` to version `4.0.1`
- https://github.com/ministryofjustice/hmpps-incentives-ui/commit/28f532fff0a6564c7da578941dc06a86ab47debd added `NOMIS_USER_ROLES_API_URL` setting to `feature.env` to run integration tests locally
=> INC-137: Sortable columns in Incentives table

integration_tests/integration/prisonerImages.spec.ts, server/app.ts, server/routes/prisonerImages.test.ts, server/routes/testutils/appSetup.ts
The prisoner images route was initially using the `standardRouter` which
was populating the current user/caseloads making additional requests.
This is useful when showing a page but a waste when a browser is getting
prisoner images' raw data.
That route now uses a simpler `imageRouter` which doesn't use the
`populateUser` middleware...however, these API calls were still happening.
The reason for this is order of the routes wiring. The `/` route (which
still uses the `standardRouter`) was still running because it was more
generic. Move it last means these unnecessary requests are not made anymore.
NOTE: I've added a regression test - which would fail if the
`app.use('/', ...` is moved back above the prisoner images route) -
and also a test for the authentication requirement of this …
=> INC-162: unnecessary API calls when getting prisoner images

server/app.ts, server/routes/all.ts, server/routes/testutils/appSetup.ts
Removed duplication between real express app and test express app.
The test express app should be as similar as possible to the real expess
app (the one determining how users' traffic is handled). This should
reduce chances of tests running against a different version of the routing
as before.
In addition, now to add a route only one file needs to change instead of
two (easy to miss)
=> INC-249: Middleware refactoring

package-lock.json
- Bumped dependencies with only patch number change
- Bumped dependencies with only minor number change
These should be safe enough to upgrade as they _shouldn't_ break compatibility (unit and integration tests passed and from cursory manual test locally things seems fine)
=> Bumped backward-compatible dependencies

server/views/pages/changeLocation.njk, server/views/pages/incentives-table.njk
(also fixed '–' in incentive table page's title for consistency)
=> Set page title for location selection page

server/middleware/setUpWebSecurity.ts, server/views/partials/layout.njk
jQuery UI was included in all pages (as it was part of the layout
template) but it doesn't seem to be used anywhere.
Even worse, the js/css wasn't served by the application itself which is
a potential security issue.
Remove these means we can remove the CSP rules to allow requests to
code.jquery.com. It also means we can remove the
`crossOriginEmbedderPolicy: true` option which was added to avoid the
related CSP error.
=> INC-329: Removed (unused) jQuery UI and simplified CSP

server/utils/format.test.ts, server/utils/format.ts, server/utils/nunjucksSetup.ts
… because we probably won't have time-of-day information for when source data refers to
=> INC-247: Add short date formatting nunjucks filters

.circleci/config.yml
This will allow CircleCI to provision test S3 buckets with the same testing data as is packaged in this repo. When deploying to `dev` or `preprod`, CircleCI will read the appropriate k8s secret with S3 details and use AWS cli to synchronise the bucket, ensuring it is up to date and matches what would run locally and during integration tests.
=> INC-305: Provision S3 buckets with testing data in `dev` and `preprod` environments

server/views/pages/analytics/behaviour-entries/prisoners-with-entries-by-location.njk
…so that users read less into the specific colour. Yellow could indicate warning or focus.
=> INC-339: Change heat map to a tint of GDS "light purple" colour

server/routes/analyticsRouter.test.ts, server/services/analyticsService.test.ts, server/services/analyticsService.ts, server/services/analyticsServiceTypes.ts, server/testData/s3Bucket.ts
Present a generic 500 error page when:
- source data is missing
- source data fails to load or is malformed
- aggregated data is empty 🆕
… because it is better to show a message than show a broken-looking table with no contents.
=> INC-391: Analytics graph errors

server/routes/analyticsRouter.test.ts, server/routes/analyticsRouter.ts
… so that it's easier to collate feedback per-chart in Zendesk
=> INC-412: Tag analytics feedback with chart id

server/views/pages/analytics/graph-layout.njk, server/views/pages/incentives-table.njk
In two templates we were showing certain elements in the page only if
a given feature flag was on or off.
We were using `Array.prototype.push()` inside an if statement.
This works but it's a bit hairy and it can be simplified by using
nunjucks' builtin `rejectattr`:
https://mozilla.github.io/nunjucks/templating.html#rejectattr-only-the-single-argument-form
This filters out elements of an array if they have a given property
set to `true`.
=> INC-443: Simplified nunjucks templates using `rejectattr`

server/services/analyticsService.test.ts
…because "Unknown" should appear last. Though it does not matter yet as those data points do not yet show in any charts.
=> Test analytics location and characteristic sorting more thoroughly

server/views/pages/home.njk
Tile heading should say 'Incentives level and behaviour entry data'
(level, not levels)
=> Updated analytics tile copy

server/routes/analyticsRouter.test.ts, server/routes/analyticsRouter.ts, server/services/analyticsServiceTypes.ts, server/views/pages/analytics/behaviour-entries/entries-by-location.njk, server/views/pages/analytics/behaviour-entries/prisoners-with-entries-by-location.njk, server/views/pages/analytics/incentive-levels/prisoners-by-location.njk, server/views/pages/analytics/no-data-partial.njk, server/views/pages/analytics/protected-characteristics/prisoners-by-age-group.njk, server/views/pages/analytics/protected-characteristics/prisoners-by-ethnicity.njk
Minor enhancement: If source data tables for analytics charts
• cannot be found
• cannot be downloaded
• cannot be parsed
• results in an empty table
…then a message is presented to the user in place of the missing chart, rather than the generic 500 page.
=> INC-391: Present in-context error messages when graph data is unavailable

integration_tests/integration/analytics.spec.ts, integration_tests/pages/analyticsProtectedCharacteristics.ts, server/routes/analyticsRouter.test.ts, server/routes/analyticsRouter.ts, server/services/analyticsService.test.ts, server/services/analyticsService.ts, server/services/analyticsServiceTypes.ts, server/views/pages/analytics/protected-characteristics/index.njk, server/views/pages/analytics/protected-characteristics/prisoners-by-age.njk
…and ensure that “Other” or “Unknown” rows always comes last in protected characteristics charts
=> INC-352: Rename "age group" protected characteristic to simply "age"

server/data/prisonRegister.ts, server/services/analyticsService.test.ts, server/services/analyticsService.ts, server/services/analyticsServiceTypes.ts
Hide 15-17 age group (young people) from protected characteristics graphs
for non-YCS prisons.
NB: YCS = Youth Custody Service
=> INC-314: Don't show empty 15-17 age group in non-YCS prisons

server/data/prisonRegister.ts
The prison with ID `FYI` is called Feltham A in DPS (this is the prison
which may contain young people).
Updated the comment to reduce confusion between this and "Feltham" (without
the A)
=> Prison Register, fix comment about Feltham A

server/routes/analyticsRouter.test.ts, server/routes/analyticsRouter.ts, server/routes/forms/chartFeedbackForm.test.ts, server/routes/forms/chartFeedbackForm.ts, server/routes/forms/forms.ts, server/views/pages/analytics/behaviour-entries/entries-by-location.njk, server/views/pages/analytics/behaviour-entries/index.njk, server/views/pages/analytics/behaviour-entries/prisoners-with-entries-by-location.njk, server/views/pages/analytics/incentive-levels/index.njk, server/views/pages/analytics/incentive-levels/prisoners-by-location.njk, server/views/pages/analytics/protected-characteristics/index.njk, server/views/pages/analytics/protected-characteristics/prisoners-by-age.njk, server/views/pages/analytics/protected-characteristics/prisoners-by-disability.njk, server/views/pages/analytics/protected-characteristics/prisoners-by-ethnicity.njk, server/views/pages/analytics/protected-characteristics/prisoners-by-religion.njk, server/views/partials/analytics/chartFeedbackForm.njk, server/views/partials/formErrorSummary.njk
…so that templates can always rely on their existence and their methods. Previously, the only situation when a form variable was passed into the page template was when the form was submitted but did not pass validation. This made templates unintuitive (most of the time the form variable did not exist).
This paves the way to allow forms to preset initial values before a form submission.
=> INC-437: Make form instances usable when data was not submitted

assets/sass/components/_chart-colours.scss, server/utils/analytics.test.ts, server/utils/analytics.ts, server/utils/nunjucksSetup.ts, server/views/components/palette.njk, server/views/pages/analytics/incentive-levels/prisoners-by-location.njk, server/views/pages/analytics/protected-characteristics/prisoners-by-age.njk, server/views/pages/analytics/protected-characteristics/prisoners-by-disability.njk, server/views/pages/analytics/protected-characteristics/prisoners-by-ethnicity.njk, server/views/pages/analytics/protected-characteristics/prisoners-by-religion.njk, server/views/pages/analytics/protected-characteristics/prisoners-by-sexual-orientation.njk
Currently, when a prison has nobody on “Basic” the colour palette shifts so that “Standard” uses the first / light blue colour.
It’s been suggested that levels should use the same colours even when some levels are missing.
=> INC-498: Use consistent colour palette for analytics charts

renovate.json
https://dsdmoj.atlassian.net/browse/INC-556
Renovate raised https://github.com/ministryofjustice/hmpps-incentives-ui/pull/152 which attempted to pin dependencies, however we want to retain the npm dependencies semvers
=> INC-556: enable preserveSemverRanges setting

.circleci/config.yml
…because the image _from quay.io_ is never used on such a processor. The extra ~12min of build time in CircleCI is currently a waste of time and money.
=> INC-567: Stop building ARM docker image in CircleCI

server/views/pages/changeLocation.njk, server/views/pages/error.njk, server/views/pages/home.njk, server/views/pages/incentives-table.njk, server/views/partials/analytics/chartBase.njk, server/views/partials/analytics/chartBaseHeatmap.njk, server/views/partials/analytics/chartBasePercentageBars.njk, server/views/partials/analytics/chartBaseStackedPercentageBars.njk, server/views/partials/analytics/chartTrends.njk, server/views/partials/analytics/formFeedback.njk, server/views/partials/analytics/reportError.njk, server/views/partials/feedbackBanner.njk, server/views/partials/layout.njk
**Use 2 spaces** instead of tabs or 4 spaces
Leave some space around macro calls, e.g.
```nunjucks
<input type="hidden" name="_csrf" value="{{ csrfToken }}" />
{{ govukButton({
text: "Submit",
classes: "govuk-!-margin-bottom-0",
preventDoubleClick: true
}) }}
</form>
```
If a macro call uses a variable set above it's OK to not leave space between the macro call and the `set`, e.g.
```nunjucks
{# FINE #}
{% set chartUsefulField = form.getField("chartUseful") %}
{{ govukRadios({
idPrefix: form.formId + "-chartUseful",
name: "chartUseful",
fieldset: { 
```
Macro calls arguments are indented from opening `{{`, e.g.
```nunjucks
{# CORRECT #}
{{ govukButton({
text: "Submit",
classes: "govuk-!-margin-bottom-0",
preventDoubleClick: true
}) }}
{# NOT CONSISTENT (or similar) #}
{{ 
govukButton({ …
```
=> INC-567: Consistent indentation in nunjucks templates/macros

.eslintrc.json
It can be distracting while working on something to see all the red
squiggly lines because you may confuse these for syntax errors.
These style issues are now shown as warning/yellow squiggly lines instead.
So that you know they're important but not AS important as syntax errors.
**NOTE**: This doesn't change the fact warnings would cause CI to fail, so
these will need to be fixed at some point.
=> INC-567: Show ESLint issues style issues as warnings

server/routes/analyticsChartsContent.ts, server/routes/analyticsRouter.ts, server/views/pages/analytics/protectedCharacteristicTemplate.njk
- added dropdown
- moved dropdown markup in a little macro used in both PC trends charts
- tweaked dropdowns form to avoid reset of other chart selected PC group on select
- corrected hyphen character in charts content `–`
=> INC-572: Dropdown for Incentive levels PC trends

server/routes/analyticsRouter.ts
For some reason (probably messed up git stash/rebase) code was still
using hardcoded value instead of query param value (meaning non-Age
PC would always have 0 rows matching)
=> INC-572: Fix Incentive levels PC trends not using correct PC group

tsconfig.json
… in order to not try to compile extraneous TS/JS code (for example, jest-coverage output)
=> INC-567: Exclude folders without server-side code from typescript compilation

helm_deploy/values-prod.yaml
The `LimitRange` k8s resource in the `prod` namespace has been updated
but the limit on the Pods also need to change accordingly.
See: `generic-service` helm chart's values file:
https://github.com/ministryofjustice/hmpps-helm-charts/blob/main/charts/generic-service/values.yaml#L73-L83
=> INC-588: Increase k8s resource limit

server/routes/incentivesTable.test.ts, server/views/pages/incentives-table.njk
When the 'Days since last review'/'Days on level' columns were removed a info banner highlighting this was
removed while data was being "investigated".
We want to remove this info banner now.
=> INC-594: Remove info banner from Incentives table pages

server/views/pages/analytics/protectedCharacteristicTemplate.njk
If one of the other 2 selectors on the page are used, they anchor to their associated heading. That anchor is preserved when this selector is used, so it's possible for this form to take you to the wrong part of the page.
=> Anchor protected characteristic selector to top of page

server/views/partials/analytics/layout.njk
An `a` element only contained within `div`s has a default/arbitrary size
=> INC-590: Use correct size for link to switch region view

server/services/analyticsService.test.ts, server/services/analyticsService.ts
I've also made the `AnalyticsService` a bit more explicit by introducing a few functions (e.g. `isNational()`, `isRegional()`, `isPrisonLevel()`) so that conditions are more clear.
=> INC-628: Show prison names in regional charts (not prisons IDs)

helm_deploy/values-dev.yaml, helm_deploy/values-prod.yaml
tried it out in `preprod` with [oha](https://github.com/hatoo/oha) and it behaved pretty well. admittedly, the data volumes are much smaller. memory remained reasonable whilst CPU spiked.
=> INC-612: Enable file-based cache in all environments

assets/sass/components/_chart-colours.scss, server/utils/analytics.test.ts, server/utils/analytics.ts
… which should not be needed as the source data is pre-processed before it reaches this app and should have no incentive levels other than:
• Basic
• Standard
• Enhanced
• Enhanced 2
• Enhanced 3
• and a catch-all-others: “New incentive”
I.e. 6 colours should have been sufficient anyway
=> INC-638: Add further fallback colours to the chart palette

integration_tests/e2e/analytics/behaviourEntries.cy.ts, integration_tests/e2e/analytics/incentiveLevels.cy.ts, server/views/pages/analytics/behaviourEntries.njk, server/views/pages/analytics/incentiveLevels.njk, server/views/partials/analytics/chartTrends.njk
The "total" row incorrectly showed "Prison population" at national and
regional level while it should say "National population" and "Total group
population" respectively.
=> INC-666: Fix population labels for national/regional trends charts

helm_deploy/hmpps-incentives-ui/Chart.yaml, helm_deploy/hmpps-incentives-ui/values.yaml
…retaining the existing one so that traffic slowly migrates to the new one.
C.f. [hmpps-helm-charts#1.5](https://github.com/ministryofjustice/hmpps-helm-charts/releases/tag/generic-service-1.5.0)
=> INC-668: Use latest shared helm chart to create new ingress controller

server/views/partials/analytics/layout.njk
Attempt to fix:
> Refused to apply inline style because it violates the following Content
> Security Policy directive: "style-src 'self' https://*.hotjar.com
> 'unsafe-inline' 'nonce-28d71b7d82e721525528e91165111d8e'".
> Note that 'unsafe-inline' is ignored if either a hash or nonce value is
> present in the source list.
=> INC-674: hotjar CSP: unsafe-inline doesn't work with nonce

helm_deploy/hmpps-incentives-ui/values.yaml
We got a recording in hotjar but page has not style (so charts are not
showing correctly for example).
This is because hotjar is unable to retrieve the CSS files as mentioned
in their docs:
https://help.hotjar.com/hc/en-us/articles/115011822728-Troubleshooting-FAQs-for-Recordings#why-do-the-pages-look-brokenno-css-loading
This adds hotjar IP addresses to allowlist:
https://help.hotjar.com/hc/en-us/articles/115011789288
=> INC-674: Add hotjar servers to IP allowlist

.circleci/config.yml, Dockerfile, package-lock.json, package.json, renovate.json, server/utils/format.ts
…and maintain formatting of dates to match older versions: v16.17 is built against a new ICU library which formats dates differently (`19 August 2022 at 10:12` instead of `19 August 2022, 10:12`).
=> Upgrade to node 16.17

server.ts, server/config.ts, server/routes/analyticsPrecacheTables.ts, server/routes/analyticsRouter.ts
…on startup and hourly so that the first requests do not attempt to load 6+ source tables concurrently.
This hopefully alleviates out-of-memory errors and pod restarts.
=> INC-707: Warm up analytics data cache

server/routes/analyticsPrecacheTables.ts
…for the test data that's packaged for testing otherwise an error is thrown for some charts and not all tables get pre-cached in `preprod` or locally.
=> INC-707: Warm up analytics data cache using filters that return non-empty charts

server/data/prisonRegister.test.ts, server/data/prisonRegister.ts, server/routes/analyticsRouter.test.ts, server/routes/analyticsRouter.ts, server/services/analyticsService.test.ts, server/services/analyticsService.ts
…which is to identify establishments that house 15-17 year olds. That is, the Youth Custody Service (a subset of Young Offender Institutions) and Women's Estate.
This distinction is only used to determine whether a "15-17" age group should appear by default (even when empty) in protected characteristics analytics charts.
=> Restructure the prison register to make its purpose clearer

server/data/hmppsAuthClient.ts, server/data/incentivesApi.ts, server/data/nomisUserRolesApi.ts, server/data/prisonApi.ts, server/data/restClient.ts
…so that an ` as ` type assertion is unnecessary and the desired type is simply a parameter.
=> Improve REST client response types

server/data/incentivesApi.test.ts, server/data/incentivesApi.ts, server/routes/reviewsTable.test.ts, server/routes/reviewsTable.ts, server/testData/incentivesApi.ts, server/utils/sortableTable.test.ts, server/utils/sortableTable.ts, server/views/pages/reviewsTable.njk
NB: sort & order options have been renamed to use upper snake case because incentives-api follows Java & Spring Data convention
Depends on [api#270](https://github.com/ministryofjustice/hmpps-incentives-api/pull/270)
=> INC-843: Update sorting parameters to match incentive-api's contract

server/data/incentivesApi.ts, server/routes/reviewsTable.test.ts, server/routes/reviewsTable.ts
In the user interface, pages are still numbered starting from 1 as users would expect. However, incentives-api now starts counting pages from 0.
Depends on [api#277](https://github.com/ministryofjustice/hmpps-incentives-api/pull/277)
=> INC-931: Use 0-based page numbering for incentives reviews api

.prettierrc.json
cf. [hmpps-template-typescript#135](https://github.com/ministryofjustice/hmpps-template-typescript/pull/135)
=> Make prettier rules match eslint in terms of trailing commas

assets/js/gaSendEvents.js, server/routes/reviewsTable.ts, server/utils/sortableTable.test.ts, server/utils/sortableTable.ts, server/views/pages/incentives-table.njk, server/views/pages/reviewsTable.njk
Similar to what we were tracking in the old Behaviour table:
- track clicks on Incentive levels tabs
- track sorting of table
- track clicks on links in the table
I've made the tracking JavaScript code static and moved into an asset file (now used by both old and new table)
=> INC-971: GA tracking for new Reviews table

assets/sass/application.scss, server/views/pages/reviewsTable.njk
This is to reduce the change of text being put on the next line too early looking odd.
=> INC-998: Incraese notification banner max width

server/routes/reviewsTable.test.ts, server/routes/reviewsTable.ts
When the user didn't select any incentive level yet page will show the 'Basic' level instead of the prison default level. If 'Basic' is not available at the prison for whatever reason the first level will be shown (this behaviour was there before).
Users want to focus on prisoners on 'Basic' so that they can be reviewed and possibly moved to a better incentive level as soon as possible.
=> INC-1040: Reviews table: 'Basic' tab selected by default

server/routes/reviewsTable.test.ts, server/routes/reviewsTable.ts
Minor tweak to #379
• Find basic level using code rather than human-readable description as it's likely to be more permanent
• Make test cases reflect the fact that basic is now the default tab rather than the default level
=> INC-1040: Reviews table should show basic level by default

.circleci/config.yml, Dockerfile, package.json, renovate.json
…which now includes npm v9 as was [specified in upstream template](https://github.com/ministryofjustice/hmpps-template-typescript/blob/92b5a338218aed85add3ddb524168ef301a5d47a/package.json#L33)
=> Update minor node version

server/views/pages/reviewsTable.njk
Reduced the margin/distance between the Incentive level names and the corresponding overdue number as discussed with Stevey/Igor.
=> INC-1075: Tweaked style of Overdue "dashboard" in 'Reviews' table

server/routes/reviewsTable.ts
This is to reflect recent API changes (INC-805) to show the number of behaviour entries since last review but limited to the last 3 months.
New wording is:
- Positive behaviours since last review (up to 3 months)
- Negative behaviours since last review (up to 3 months)
⚠️ **NOTE**: This is depends on:
- Incentives API being deployed to `prod`: https://github.com/ministryofjustice/hmpps-incentives-api/pull/360
- which in turn depends on new Prison API's `POST /api/case-notes/usage-by-types` endpoint being deployed to `prod` environment : https://github.com/ministryofjustice/prison-api/pull/1504
=> INC-1106: Rename behaviours columns in 'Reviews' table

LICENSE, integration_tests/e2e/analytics/behaviourEntries.cy.ts, integration_tests/e2e/analytics/incentiveLevels.cy.ts, integration_tests/e2e/login.cy.ts, integration_tests/e2e/prisonIncentiveLevels.cy.ts, integration_tests/e2e/reviewsTablePage.cy.ts, integration_tests/mockApis/auth.ts, integration_tests/mockApis/incentivesApi.ts, integration_tests/mockApis/wiremock.ts, integration_tests/pages/home.ts, integration_tests/pages/page.ts, integration_tests/pages/prisonIncentiveLevels/prisonIncentiveLevel.ts, integration_tests/pages/prisonIncentiveLevels/prisonIncentiveLevelAddForm.ts, integration_tests/pages/prisonIncentiveLevels/prisonIncentiveLevelDeactivateForm.ts, integration_tests/pages/prisonIncentiveLevels/prisonIncentiveLevelEditForm.ts, integration_tests/pages/prisonIncentiveLevels/prisonIncentiveLevels.ts, integration_tests/plugins/index.ts, server/routes/forms/prisonIncentiveLevelAddForm.test.ts, server/routes/forms/prisonIncentiveLevelAddForm.ts, server/routes/forms/prisonIncentiveLevelDeactivateForm.ts, server/routes/forms/prisonIncentiveLevelEditForm.test.ts, server/routes/forms/prisonIncentiveLevelEditForm.ts, server/routes/prisonIncentiveLevels.test.ts, server/routes/prisonIncentiveLevels.ts, server/views/pages/prisonIncentiveLevels.njk, server/views/partials/prisonIncentiveLevelEditPartial.njk
Improves on #444 by
• adding integration tests to test end-to-end user journeys
• preventing actions that would result in no level being the default in a prison
=> INC-1185: Enhance admin section to manage incentive level details in a prison

integration_tests/e2e/prisonIncentiveLevels.cy.ts, integration_tests/pages/page.ts, integration_tests/pages/prisonIncentiveLevels/prisonIncentiveLevel.ts, integration_tests/pages/prisonIncentiveLevels/prisonIncentiveLevelAddForm.ts, integration_tests/pages/prisonIncentiveLevels/prisonIncentiveLevelDeactivateForm.ts, integration_tests/pages/prisonIncentiveLevels/prisonIncentiveLevelEditForm.ts, integration_tests/pages/prisonIncentiveLevels/prisonIncentiveLevels.ts, server/data/incentivesApi.ts, server/routes/prisonIncentiveLevels.test.ts, server/routes/prisonIncentiveLevels.ts, server/sanitisedError.test.ts, server/sanitisedError.ts, server/views/pages/prisonIncentiveLevelDeactivateForm.njk, server/views/partials/messages.njk
…and show a specific custom message when a level cannot be deactivated  because there are prisoners on it.
Turns out that api errors were incorrectly handled before: the error thrown was not directly what the api returned but wrapped inside `SanitisedError`
=> INC-1212: Handle api errors properly when incentive levels are being modified

server/views/pages/reviewsTable.njk, server/views/partials/about-analytics/appendix.njk
Previous DAC audits had asked for tables to have captions so might as well add screen-reader-only versions
=> Improve accessibility of tables by adding hidden captions

integration_tests/e2e/aboutNationalPolicy.cy.ts, integration_tests/e2e/analytics/behaviourEntries.cy.ts, integration_tests/e2e/analytics/incentiveLevels.cy.ts, integration_tests/e2e/analytics/pgdRegionSelection.cy.ts, integration_tests/e2e/analytics/protectedCharacteristics.cy.ts, integration_tests/e2e/prisonIncentiveLevels.cy.ts, integration_tests/e2e/prisonerImages.cy.ts, server/data/prisonApi.ts, server/routes/home.ts, server/routes/homeRouter.test.ts, server/routes/selectLocation.ts, server/testData/nomisIUserRolesApi.ts, server/testData/prisonApi.ts, server/views/pages/home.njk
There exist users with case loads that aren’t real locations so it does not make sense to show them sections of the site that only work in prisons.
Such users are:
• LSAs when using their special account (with `CADM_I` role)
• central admins who are never in a prison
The former group can now only see the prison-group analytics charts.
The latter group can now only see the prison-group analytics charts and global incentive level admin section.
---
Effectively:
- all users can see the prison-group analytics charts and about page for visualisations
- central admins, non-prison-based users, with `MAINTAIN_INCENTIVE_LEVELS` role also see global incentive level admin section
- all prison-based users also see incentive reviews sections and all analytics charts
- LSAs, using their normal …
=> INC-1238: Show location-based tiles on home page only when appropriate

package-lock.json, server/routes/incentiveLevels.ts, server/routes/prisonIncentiveLevels.test.ts, server/routes/prisonIncentiveLevels.ts
This is useful for new prisons so that they adopt the standard set of levels.
Additionally, if a prison has no default-for-admissions level (a data inconsistency problem) it will automatically gain Standard.
=> INC-1250: Automatically add any missing required incentive levels to a prison

server/utils/nunjucksSetup.ts
(slight modification to [hmpps-template-typescript#188](https://github.com/ministryofjustice/hmpps-template-typescript/pull/188))
At the moment the cache is linked to the start up time of pod, so get unnecessary cache misses for each pod in the cluster and also when pods restart
This ties the cache to the git ~short~ hash of the deployment
=> Tie css cache to version of application

server/routes/forms/incentiveLevelCreateForm.test.ts, server/routes/forms/incentiveLevelCreateForm.ts, server/routes/forms/incentiveLevelEditForm.test.ts, server/routes/forms/incentiveLevelEditForm.ts, server/routes/forms/incentiveLevelReorderForm.test.ts, server/routes/incentiveLevels.test.ts, server/routes/incentiveLevels.ts
Whilst the exact error messages and level name length limits are being determined, we can already put in the hard 30-character limit. That’s the maximum that the incentives-api will allow. As it happens, NOMIS permits up to 40 characters, but this has been deemed excessive.
=> INC-1233: Preliminary incentive level name validation

server/services/analyticsServiceUtils.test.ts, server/services/analyticsServiceUtils.ts
The source data was expected to always provide a `pgd_region` (one of https://github.com/ministryofjustice/hmpps-incentives-ui/blob/77e78f4cfe04360679871e37aeae75d4113c1de4/server/services/pgdRegionService.ts#L8-L29) but it’s become necessary to handle nulls. It’s likely that the data-exporting pipeline does not handle new/unexpected prisons.
=> INC-1270: Handle location and characteristic labels being null in analytics charts source data

bin/download-source-tables.ts, bin/list-source-tables.ts, bin/truncate-source-table.ts, integration_tests/tsconfig.json, server/routes/analyticsPrecacheTables.ts, server/routes/analyticsRouter.ts, server/services/analyticsView.test.ts, server/services/analyticsView.ts, server/services/pgdRegionService.test.ts, server/services/pgdRegionService.ts, server/testData/s3Bucket.ts, tsconfig.json
… so that we don't need to ignore upcoming deprecations.
This does mean that some of the analytics charts required more type annotations which feel a little awkward but I wanted to change as little as possible by way of resulting JS.
=> Add type assertions to prevent "implicit any" errors

.circleci/config.yml, server/config.ts, server/testData/s3Bucket/README.md
CircleCI uses long-lived IAM access keys to upload test data into S3 buckets. Those credentials are being removed so the deployment pipeline cannot update S3 anymore from CircleCI.
=> INC-1280: Make non-production S3 buckets entirely read-only

integration_tests/e2e/aboutAnalytics.cy.ts, integration_tests/e2e/aboutNationalPolicy.cy.ts, integration_tests/e2e/analytics/behaviourEntries.cy.ts, integration_tests/e2e/analytics/incentiveLevels.cy.ts, integration_tests/e2e/analytics/pgdRegionSelection.cy.ts, integration_tests/e2e/analytics/protectedCharacteristics.cy.ts, integration_tests/e2e/home.cy.ts, integration_tests/e2e/incentiveLevels.cy.ts, integration_tests/e2e/locationSelection.cy.ts, integration_tests/e2e/prisonIncentiveLevels.cy.ts, integration_tests/e2e/reviewsTablePage.cy.ts, integration_tests/pages/page.ts, server/middleware/breadcrumbs.ts, server/routes/analyticsRouter.ts, server/routes/home.ts, server/routes/incentiveLevels.ts, server/routes/prisonIncentiveLevels.ts, server/routes/reviewsTable.ts
i.e. pop off the last item from every page’s breadcrumb list. Now, the last item is tested for every page.
=> Follow latest DPS standards for breadcrumbs so that the current page is not presented

integration_tests/e2e/incentiveLevels.cy.ts, integration_tests/e2e/prisonIncentiveLevels.cy.ts, server/routes/incentiveLevels.ts, server/routes/prisonIncentiveLevels.ts
The incentive level and prison incentive level _list_ pages should not include themselves in the breadcrumbs list
Fixes changes in #564
=> Fix breadcrumbs

.circleci/config.yml
…and skip path ".cache/Cypress" which does not exist.
Copied from [non-api#103](https://github.com/ministryofjustice/hmpps-non-associations/pull/103)
=> Fix CircleCI workspace persistence to include built front-end assets

integration_tests/mockApis/incentivesApi.ts, integration_tests/plugins/index.ts, server/data/incentivesApi.ts
`GET /iep/levels/{prisonId}` has been deprecated for a long time and will be removed at some point soon.
The UI doesn't use this endpoint anymore but there were still a couple of methods related to this endpoint that can be removed.
=> INC-1296: Removed vestigial referenced to deprecated endpoint

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml
Enable 'scheduled downtime' feature of generic-service helm chart: https://github.com/ministryofjustice/hmpps-helm-charts/tree/main/charts/generic-service#scheduled-downtime
> To enable this feature, you first need to add a `scheduled-downtime-serviceaccount`
> Service Account to your namespace, with permissions to scale your deployment.
The required kubernetes `ServiceAccount` is already there:
- `dev`: https://github.com/ministryofjustice/cloud-platform-environments/blob/b534875bb2347de40543ceabc3d5ce102b6514fd/namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/scheduled-downtime.tf
- `preprod`: https://github.com/ministryofjustice/cloud-platform-environments/blob/b534875bb2347de40543ceabc3d5ce102b6514fd/namespaces/live.cloud-platform.service.justice.gov …
=> INC-1235: Stop non-prod instances during non-working hours

.circleci/config.yml, helm_deploy/values-preprod.yaml
…keeping `prod` unchanged for now to test the set actually applied to the ingress.
Expectation is that 5 SSCL ranges will disappear, but they are very likely to not be needed.
=> Move `preprod` to use shared IP address allow lists

docker-compose-test.yml
…because [minio/mc image no longer includes it](https://github.com/minio/minio/pull/18329) (nor wget, netcat, socat or even package management tools)
=> Stop using `curl` in docker compose init script

renovate.json
This reverts commit 67ca9cbf294ee3176a94142221182ce8357f5a70.
=> Revert "Auto-merge renovate’s non-major npm updates (#664)"

server/data/prisonApi.test.ts, server/data/prisonApi.ts, server/data/restClient.ts
`prison-api` now (sensibly!) returns 403 instead of 404 if token is unauthorised. We should swallow the error and display a placeholder rather than a broken image; same as is done when none is found.
=> INC-1335: Display default image when user is not authorised to view a prisoner’s photo

server/routes/prisonerIncentiveLevelDetails.ts
Comparison was incorrectly using the text input instead of parsed & validated `Date`
=> INC-1337: Fix from/to date filter validation on incentive history page

.eslintrc.json, helm_deploy/hmpps-incentives-ui/values.yaml, package-lock.json, package.json, server/config.ts, server/data/hmppsAuditClient.test.ts, server/data/hmppsAuditClient.ts, server/services/auditService.test.ts, server/services/auditService.ts
Copied from [upstream template](https://github.com/ministryofjustice/hmpps-template-typescript/pull/327) but the audit client is _not_ used in any route
=> Add (disabled) audit client (hmpps-template-typescript#327)

server/utils/nunjucksSetup.ts
The app runs from within the `/dist` folder into which assets are built along with the *manifest* file. This manifest file is used from within nunjucks templates to map local paths to versioned assets.
However, tests run from the actual sources and cannot find the manifest file, leading to a wall of inconsequential error messages.
For now it’s easiest to silence this error in test mode. `jest` tests don’t actually even try to load any assets; there is no server running.
Once the template project decides on a better workaround, we can cherry-pick it and remove this solution.
=> INC-1335: Silence asset manifest file error during tests

server/middleware/setUpStaticResources.ts
…which is available when running locally and (crucially) in deployed versions of the app
=> INC-1335: Load user guide PDF from /dist/ folder

integration_tests/mockApis/frontendComponents.ts, integration_tests/mockApis/wiremock.ts, server/data/frontendComponentsClient.ts, server/middleware/frontendComponents.test.ts, server/middleware/frontendComponents.ts, server/sanitisedError.test.ts, server/sanitisedError.ts, server/testData/frontendComponents.ts
`/header` & `/footer` endpoints are deprecated and [`/components`](https://frontend-components.hmpps.service.justice.gov.uk/api-docs/#/default/get_components) should be used instead
copied from [hmpps-incident-reporting#201](https://github.com/ministryofjustice/hmpps-incident-reporting/pull/201)
=> INC-1335: Use non-deprecated endpoint to load DPS micro-frontend components

helm_deploy/hmpps-incentives-ui/values.yaml
…the k8s secret itself is created by terraform from a shared DPS secret in a AWS systems manager parameter
Ref: [hmpps-template-typescript#485](https://github.com/ministryofjustice/hmpps-template-typescript/pull/485)
=> INC-1335: Get Azure Application Insights settings from kubernetes secret directly

integration_tests/e2e/prisonIncentiveLevels.cy.ts, server/routes/prisonIncentiveLevels.test.ts, server/views/pages/prisonIncentiveLevel.njk, server/views/partials/prisonIncentiveLevelEditPartial.njk
The number of visiting orders (and privileged visiting orders) a prisoner receives for a given incentive level at a prison is now controlled in the incentives API.
The information presented to staff as they input those numbers is very limited - this means that some prisons have inputted very high numbers in that service. We also get queries from staff asking what the allowances are and when they will get added.
This PR improves the information shown to staff, including:
* how frequently VOs get updated
* how frequently PVOs get updated
* if and when the VOs or PVOs ‘expire'
By improving the information in the Incentive service, we can help staff understand what the VO and PVO numbers will mean for their establishment and prisoners in that establishment.
=> Fixes VB-4369 - improves guidance on VOs linked to incentive levels

helm_deploy/hmpps-incentives-ui/values.yaml, helm_deploy/values-prod.yaml
Use UTC and ensure API starts before UI/first retry-dlq run and stops after UI and last retry-dlq run.
- [6:49am API starts](https://github.com/ministryofjustice/hmpps-incentives-api/pull/687/files#diff-5ef4f2b0d47cd40c718eb93fc47bb057e8d41c41ae435aa4214f852ce1199282R16-R17)
- 7:00am UI starts
- [7:00am retry-dlq run every 10 minutes](https://github.com/ministryofjustice/hmpps-helm-charts/blob/f210af4475dd27689621b491a63d69bbe683de0e/charts/generic-service/values.yaml#L256)
- ...
- 9:50pm retry-dlq last run for the day
- 9:50pm UI stops
- 9:58pm API stops
Sibling of similar [API PR](https://github.com/ministryofjustice/hmpps-incentives-api/pull/687).
=> IR-1136: Tweaked start/stop schedules

server/views/pages/incentiveLevel.njk, server/views/pages/incentiveLevelCreateForm.njk, server/views/pages/incentiveLevelEditForm.njk, server/views/pages/incentiveLevels.njk, server/views/pages/prisonIncentiveLevel.njk, server/views/pages/prisonIncentiveLevelAddForm.njk, server/views/pages/prisonIncentiveLevelDeactivateForm.njk, server/views/pages/prisonIncentiveLevelEditForm.njk, server/views/pages/prisonIncentiveLevelNextAddForm.njk, server/views/pages/prisonIncentiveLevels.njk
This PR updates the incentive level pages from one-half width to two-thirds width. The current UI looks quite bunched.
=> Updated incentive level page widths to two-thirds
