ministryofjustice/hmpps-incentives-ui

- .circleci/config.yml
- helm_deploy/values-preprod.yaml
Part of ticket: https://trello.com/c/w2bGwZHv
> Promote to `preprod` environment

- .circleci/config.yml
- helm_deploy/values-prod.yaml
Part of ticket: https://trello.com/c/w2bGwZHv
> Promote to `prod` environment

- .circleci/config.yml
Not the typescript template channel.
> CircleCI: Send Slack notification to DPS channels

- integration_tests/integration/incentivesTable.spec.ts
- integration_tests/integration/locationSelection.spec.ts
- integration_tests/mockApis/prisonApi.ts
- integration_tests/plugins/index.ts
- server/app.ts
- server/data/prisonApi.ts
- server/routes/prisonerImages.test.ts
- server/routes/prisonerImages.ts
- server/routes/testutils/appSetup.ts
- server/views/pages/incentives-table.njk
Show prisoner images in behaviour entries table.
> INC-125: Show prisoner images

- integration_tests/integration/incentivesTable.spec.ts
- integration_tests/pages/behaviourEntriesPage.ts
- server/routes/index.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/incentives-table.njk
Also added integration tests for these DPS links
> INC-152: DPS links have from date set to 3 months ago

- feature.env
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- integration_tests/integration/health.spec.ts
- integration_tests/integration/incentivesTable.spec.ts
- integration_tests/integration/locationSelection.spec.ts
- integration_tests/integration/login.spec.ts
- integration_tests/mockApis/auth.ts
- integration_tests/mockApis/nomisUserRolesApi.ts
- integration_tests/mockApis/prisonApi.ts
- integration_tests/plugins/index.ts
- server/app.ts
- server/config.ts
- server/data/hmppsAuthClient.ts
- server/data/incentivesApi.ts
- server/data/nomisUserRolesApi.test.ts
- server/data/nomisUserRolesApi.ts
- server/data/nomisUserRolesApii.test.ts
- server/data/prisonApi.ts
- server/routes/imageRouter.ts
- server/routes/testutils/appSetup.ts
- server/services/behaviourService.ts
- server/services/healthCheck.ts
- server/services/userService.test.ts
- server/services/userService.ts
- server/testData/nomisIUserRolesApi.ts
- server/views/partials/locationBar.njk
Signed-off-by: mjwillis <michael.willis@digital.justice.gov.uk>
> INC-86 Use different api for user caseload.

- assets/sass/local.scss
- feature.env
- helm_deploy/hmpps-incentives-ui/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- integration_tests/integration/incentivesTable.spec.ts
- server/config.ts
- server/routes/incentivesTable.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/incentives-table.njk
- server/views/partials/feedbackBanner.njk
- server/views/partials/layout.njk
- server/views/partials/locationBar.njk
- Added feedback banner (shown in all pages as discussed during this morning planning)
- Added phase tag to make current environment more evident consistently to what happens in DPS
> INC-204: Feedback banner and phase tag

- package-lock.json
- package.json
- server/@types/express/index.d.ts
- server/middleware/setUpWebSession.ts
- server/services/healthCheck.ts
These changes are unlikely to make any difference.
The problem appears to be redis-related: after some time, there's a connection timeout and it does not attempt to reconnect. I have a sneaking suspicion it's to do with the `.connect()` method on the client not being awaited correctly and/or multiple clients racing.
> INC-291: Fix delayed app crashes

- integration_tests/integration/analytics.spec.ts
- server/routes/analyticsRouter.test.ts
- server/services/analyticsService.test.ts
- server/services/analyticsService.ts
NB: they now do NOT correspond to the behaviour entry graphs
> INC-286: Update incentive levels sample graph data to correspond to protected characteristics graphs

- server/views/pages/analytics/incentive-levels/prisoners-by-location.njk
- server/views/pages/analytics/protected-characteristics/prisoners-by-age-group.njk
- server/views/pages/analytics/protected-characteristics/prisoners-by-ethnicity.njk
… behaviour entry graphs do not yet have finalised content
> INC-373: Add guidance content to incentive-level-type graphs

- .circleci/config.yml
… which uploaded files correctly but exited with an error code anyway
> INC-305: Fix CircleCI shell script to provision S3 buckets

- integration_tests/integration/analytics.spec.ts
- integration_tests/pages/analyticsIndex.ts
- server/routes/analyticsRouter.test.ts
- server/views/pages/analytics/index.njk
- server/views/pages/home.njk
…whilst IA is being thought through.
> INC-241: Interim index page content updates

- server/app.ts
- server/errorHandler.test.ts
- server/errorHandler.ts
- server/routes/analyticsRouter.test.ts
- server/routes/testutils/appSetup.ts
- server/views/pages/pageNotFound.njk
Ref: [404](https://design-system.service.gov.uk/patterns/page-not-found-pages/) and [500](https://design-system.service.gov.uk/patterns/problem-with-the-service-pages/)
> INC-391: Use GDS copy for 404 and 500 pages

- server/services/analyticsService.ts
…because the service erroneously collected _all_ possible levels from the source data set.
It should instead use the levels after the source data has been pre-filtered.
Also, use the actual number of levels in the data set during mapping step rather than 4!
> INC-392: Fix level set in charts that show data by-level

- server/routes/incentivesTable.test.ts
- server/views/pages/incentives-table.njk
Updated as per JIRA comment: https://dsdmoj.atlassian.net/browse/INC-384?focusedCommentId=206883
> Copy of 'Incentives table' message

- server/routes/analyticsRouter.test.ts
- server/routes/analyticsRouter.ts
- server/routes/forms/chartFeedbackForm.test.ts
- server/routes/forms/chartFeedbackForm.ts
- server/routes/forms/forms.ts
Forms now need to be subclasses so that validation is forced to happen at the right time
> INC-437: Better form class structure 

- server/routes/incentivesTable.test.ts
- server/views/pages/incentives-table.njk
As per latest version in JIRA comment:
https://dsdmoj.atlassian.net/browse/INC-384?focusedCommentId=207681
> INC-384: Updated copy of message above 'Incentives table'

- bin/download-source-tables.ts
- bin/list-source-tables.ts
These are simple command line tools, run manually on pods (`kubectl exec …`), for testing/debugging purposes rather than for use in the website/application.
> INC-462: Bucket tools

- helm_deploy/values-prod.yaml
Removal of 'Days since last review' + 'Days on level'
> INC-383 Removal of 'Days since last review' & 'Days on level'

- integration_tests/pages/analyticsBehaviourEntries.ts
- server/routes/analyticsRouter.test.ts
- server/views/pages/analytics/behaviour-entries/entries-by-location.njk
- server/views/pages/analytics/behaviour-entries/index.njk
- server/views/pages/analytics/behaviour-entries/prisoners-with-entries-by-location.njk
… as the page will have other charts covering different periods
> INC-495: Move charts' time period to their subheading

- .circleci/config.yml
- .env.sample
- assets/sass/global.scss
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- integration_tests/integration/login.spec.ts
- server/config.ts
- server/utils/nunjucksSetup.ts
- server/views/partials/layout.njk
- Added "Get help" and "Terms and conditions" links
- Removed "Open Government Licence" text
> INC-442: Footer tweaks for consistency with DPS

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
**Not to be promoted to prod before May 4**
> INC-532: Release all-on-one-page protected characteristics analytics charts

- docker-compose-test.yml
- server/data/hmppsAuthClient.ts
c.f.
• [hmpps-template-typescript#87](https://github.com/ministryofjustice/hmpps-template-typescript/pull/87)
• [check-my-diary#285](https://github.com/ministryofjustice/check-my-diary/pull/285/files#diff-6e72fc85bdf9d7aa207102402a2de7cf7aec4109d2378b66921a5c70d07a4f1fL17)
> Sync with `hmpps-template-typescript`

- server/routes/analyticsRouter.ts
- server/views/pages/analytics/protectedCharacteristicTemplate.njk
https://dsdmoj.atlassian.net/browse/INC-544
> INC-544: dropdown selector to navigate between protected characteristics pages

- integration_tests/integration/analytics/analyticsBehaviourEntries.spec.ts
- integration_tests/integration/analytics/analyticsIncentiveLevels.spec.ts
- integration_tests/integration/analytics/analyticsProtectedCharacteristics.spec.ts
- integration_tests/pages/analytics.ts
- integration_tests/pages/analyticsBehaviourEntries.ts
- integration_tests/pages/analyticsIncentiveLevels.ts
- integration_tests/pages/analyticsProtectedCharacteristics.ts
We had quite few methods with almost exact logic that returned a chart
table's rows. This can be generalised.
> INC-544: Int. tests: Factored out method to get chart tables

- server/routes/analyticsRouter.ts
- server/views/pages/analytics/behaviourEntries.njk
Prisoners are **not** 'on' behaviour entries, they receive behaviour entry
types. Update headers accordingly, e.g.
From: 'Percentage and number of prisoners on each behaviour entry type [...]'
To: 'Percentage and number of prisoners receiving each behaviour entry type [...]'
> INC-564: Copy tweaks to charts' headers

- server/services/analyticsService.ts
https://dsdmoj.atlassian.net/browse/INC-565
> INC-565: Copy tweaks to charts' data source

- server/routes/analyticsRouter.ts
> INC-564: Add word 'type' in 3rd PC chart header

- integration_tests/integration/analytics/behaviourEntries.spec.ts
- integration_tests/integration/analytics/incentiveLevels.spec.ts
- integration_tests/integration/analytics/protectedCharacteristics.spec.ts
- integration_tests/integration/analytics/utils.ts
- integration_tests/pages/analytics/behaviourEntries.ts
- integration_tests/pages/analytics/incentiveLevels.ts
- integration_tests/pages/analytics/index.ts
- integration_tests/pages/analytics/protectedCharacteristics.ts
- integration_tests/pages/home.ts
…to match file structure of other analytics code
> INC-567: Rearrange analytics integration tests

- server/data/hmppsAuthClient.ts
- server/services/healthCheck.test.ts
- server/services/userService.ts
…as suggested by SonarCloud.io
> INC-567: Fix code smells

- server/views/pages/home.njk
- server/views/pages/incentives-table.njk
- server/views/partials/analytics/reportError.njk
- server/views/partials/feedbackBanner.njk
- server/views/partials/layout.njk
- server/views/partials/locationBar.njk
Always use double quotes (`"`), unless the string itself contains double
quotes (in that case makes sense to use single quotes (`'`) rather than escape
the double quotes).
Also, don't use quotes in object properties unless they contain "odd" characters
(similarly to what we do in JS/TS).
Example:
```Nunjucks
{# CORRECT #}
myMacro({
foo: "Bar",
"baz-baz": 42,
})
{# WRONG #}
myMacro({
"foo": "Bar",
"baz-baz": 42,
})
```
> INC-567: Quotes consistency in HTML/Nunjucks templates

- server/views/partials/analytics/chartBase.njk
- server/views/partials/analytics/chartTrends.njk
https://dsdmoj.atlassian.net/browse/INC-575
> INC-575: add afterHeaderHtml param to chartBase; add id to chart headers for navigation after sub cat selection

- server/services/analyticsServiceTypes.ts
…even though these are not stored in the truncated/filtered test data packaged with this repo
> Document all columns currently available in source data

- helm_deploy/values-dev.yaml
https://dsdmoj.atlassian.net/browse/INC-575
> INC-575: enable feature flag in dev

- server/services/analyticsService.test.ts
https://dsdmoj.atlassian.net/browse/INC-572
> INC-572: analyticsService unit tests

- server/routes/analyticsChartsContent.ts
https://dsdmoj.atlassian.net/browse/INC-585
> INC-585: update PC charts to use generic content for guidance text

- integration_tests/integration/analytics/protectedCharacteristics.spec.ts
- server/routes/analyticsChartTypes.ts
- server/routes/analyticsChartsContent.ts
- server/routes/analyticsRouter.test.ts
- server/routes/analyticsRouter.ts
- server/services/analyticsService.test.ts
- server/services/analyticsService.ts
- server/services/analyticsServiceTypes.ts
- server/services/analyticsServiceUtils.test.ts
- server/services/analyticsServiceUtils.ts
- server/views/pages/analytics/protectedCharacteristicTemplate.njk
https://dsdmoj.atlassian.net/browse/INC-576
> INC-576: rename existing entries chart and update trends monthly data helpers to be relative to the report date

- assets/sass/components/_header-bar.scss
- server/views/partials/analytics/layout.njk
- server/views/partials/layout.njk
- server/views/partials/spacer.njk
https://dsdmoj.atlassian.net/browse/INC-601
Thought that we can add tests when we build INC-599
Here's a preview when I simulated passing `prisonGroup = 'National'` to `protectedCharacteristicTemplate`:
> INC-601: prison group header and link to switch page

- integration_tests/integration/analytics/prisonGroupSelection.spec.ts
- integration_tests/integration/analytics/protectedCharacteristics.spec.ts
- server/routes/all.ts
- server/routes/analyticsRouter.test.ts
- server/routes/analyticsRouter.ts
- server/views/pages/analytics/protectedCharacteristicTemplate.njk
- server/views/partials/analytics/layout.njk
https://dsdmoj.atlassian.net/browse/INC-599
> INC-599: routing to prison group

- integration_tests/e2e/analytics/behaviourEntries.cy.ts
- integration_tests/e2e/analytics/incentiveLevels.cy.ts
- integration_tests/e2e/analytics/protectedCharacteristics.cy.ts
- server/routes/analyticsRouter.test.ts
- server/routes/analyticsRouter.ts
- server/services/analyticsServiceTypes.ts
- server/testData/s3Bucket/behaviours_28d_pgdregion/empty.json
- server/testData/s3Bucket/behaviours_28d_prison/empty.json
- server/testData/s3Bucket/incentives_latest_narrow/empty.json
- server/testData/s3Bucket/incentives_trends/empty.json
https://dsdmoj.atlassian.net/browse/INC-614
> INC-614: display national and regional charts

- server/views/pages/home.njk
https://dsdmoj.atlassian.net/browse/INC-600
> INC-600: small copy tweak on the tile

- server/middleware/setUpWebSecurity.ts
[Ref](https://security-guidance.service.justice.gov.uk/implement-security-txt/#securitytxt)
> Update security.txt link as the guidance has been changed

- assets/sass/components/_chart-table-bars.scss
- assets/sass/components/_chart-table-heatmap.scss
- server/routes/analyticsChartsContent.ts
- server/routes/analyticsRouter.ts
- server/views/pages/analytics/behaviourEntries.njk
- server/views/pages/analytics/incentiveLevels.njk
- server/views/pages/analytics/protectedCharacteristicTemplate.njk
- server/views/partials/analytics/chartBaseHeatmap.njk
- server/views/partials/analytics/chartBasePercentageBars.njk
- server/views/partials/analytics/chartBaseStackedPercentageBars.njk
- server/views/partials/analytics/chartBehaviourEntries.njk
- server/views/partials/analytics/chartPopulation.njk
- server/views/partials/analytics/chartPrisonersOnLevels.njk
- server/views/partials/analytics/chartPrisonersWithBehaviourEntries.njk
…for charts displaying lists of regions / prison groups because they have really long names.
> INC-602: Give label columns more space in national view

- server/views/components/card/card.njk
- server/views/pages/incentives-table.njk
- server/views/partials/feedbackBanner.njk
… as it adds no styles given `$govuk-global-styles: true`
> Remove unnecessary `govuk-link` class from links

- integration_tests/e2e/analytics/protectedCharacteristics.cy.ts
- server/routes/analyticsChartsContent.ts
- server/routes/analyticsRouter.test.ts
- server/routes/analyticsRouter.ts
- server/services/analyticsView.ts
- server/views/pages/analytics/behaviourEntries.njk
- server/views/pages/analytics/incentiveLevels.njk
- server/views/pages/analytics/protectedCharacteristicTemplate.njk
https://dsdmoj.atlassian.net/browse/INC-641
> INC-641: update chart titles and copy

- .env.sample
- feature.env
- helm_deploy/hmpps-incentives-ui/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- server/config.ts
- server/routes/analyticsRouter.test.ts
- server/routes/analyticsRouter.ts
- server/views/pages/home.njk
https://dsdmoj.atlassian.net/browse/INC-590
> INC-590: remove feature flag in order to release to prod

- LICENSE
- README.md
- helm_deploy/README.md
… listing ancillary services and monitoring solutions
> INC-348: Update documentation to be particular to this application

- helm_deploy/hmpps-incentives-ui/values.yaml
…by removing the old one.
C.f. https://github.com/ministryofjustice/hmpps-helm-charts/releases/tag/generic-service-1.5.0
> INC-668: Complete upgrade of ingresses

- server/middleware/setUpWebSecurity.ts
See hotjar docs: https://help.hotjar.com/hc/en-us/articles/115011640307-Content-Security-Policies
> INC-674: Fix hotjar CSP (requires unsafe-inline)

- package-lock.json
- package.json
(jest v29 has incompatible peer dependencies)
> Update dependencies, ignoring jest

- helm_deploy/hmpps-incentives-ui/templates/stale-analytics-data.yaml
https://dsdmoj.atlassian.net/browse/INC-834
> INC-834: include our team name in the analytics source data alert

- assets/sass/application.scss
- assets/sass/components/_reviews-table.scss
- server/routes/reviewsTable.test.ts
- server/routes/reviewsTable.ts
- server/utils/nunjucksSetup.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/pages/reviewsTable.njk
• Adds reviews table with sample content
• Display of table rows is now complete with links etc.
Pagination and sorting will be done in upcoming PR…
> INC-755: Placeholder UI for upcoming reviews table

- server/routes/homeRouter.test.ts
- server/views/pages/home.njk
(there wasn't a dedicated story for this and i missed it previously)
> INC-744: Show updated tile for new reviews table

- integration_tests/e2e/incentivesTable.cy.ts
- integration_tests/mockApis/prisonApi.ts
- server/data/prisonApi.ts
- server/data/restClient.ts
- server/routes/all.ts
- server/routes/prisonerImages.test.ts
- server/routes/prisonerImages.ts
- server/views/pages/incentives-table.njk
- server/views/pages/reviewsTable.njk
- INC-899 Use prisoner number to render image
- INC-899 Use prisoner number to render image
> INC-899 Use prisoner number for images rather than face Id

- server/data/incentivesApi.ts
- server/testData/incentivesApi.ts
- server/views/pages/incentives-table.njk
- server/views/pages/reviewsTable.njk
…now that this app loads the photos using prisoner number
> INC-892: Remove prisoner image ID from contract with incentives-api

- server/data/incentivesApi.test.ts
- server/data/incentivesApi.ts
- server/testData/incentivesApi.ts
Depends on [api#257](https://github.com/ministryofjustice/hmpps-incentives-api/pull/257)
> INC-884: Pass incentive level filter to incentives api to get V2 reviews table

- server/routes/reviewsTable.test.ts
- server/routes/reviewsTable.ts
- server/views/pages/reviewsTable.njk
…when there are no prisoners at given location on selected level
> INC-950: Show informative message rather than empty table

- assets/js/application.js
- integration_tests/e2e/home.cy.ts
- integration_tests/pages/home.ts
> INC-960: Allow cards on the home page to be clickable anywhere

- package-lock.json
- package.json
- renovate.json
https://dsdmoj.atlassian.net/browse/INC-972
> INC-972: configure Renovate to bump typescript

- package-lock.json
- package.json
- renovate.json
https://dsdmoj.atlassian.net/browse/INC-972
> INC-972: configure Renovate to bump govuk-frontend

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
See also: [digital-prison-services#2313](https://github.com/ministryofjustice/digital-prison-services/pull/2313)
Should be deployed on 4 Jan.
> INC-953: Enable new reviews table for private beta technical check

- server/views/pages/reviewsTable.njk
Second paragraph should be:
> Your local policy should ensure incentive reviews take place within the guidelines of the national policy.
See Slack: https://mojdt.slack.com/archives/C02L4963K3N/p1673024595398659?thread_ts=1673024064.287529&cid=C02L4963K3N
> INC-998: Copy change to policy notification banner

- renovate.json
https://dsdmoj.atlassian.net/browse/INC-1039
> INC-1039: source Renovate config from shared HMPPS repo

- renovate.json
https://dsdmoj.atlassian.net/browse/INC-1039
> INC-1039: fix #374

- server/routes/incentivesTable.test.ts
- server/routes/reviewsTable.ts
- server/views/pages/incentives-table.njk
Reverts ministryofjustice/hmpps-incentives-ui#401 - Wording needs approval first
> Revert "INC-1106 💄 Update wording on review pages to match behaviour count logic - last review date or previous 3 months (if older)"

- server/routes/homeRouter.test.ts
- server/views/pages/home.njk
And tweaked cards' copy according to new design.
> INC-1090: Group home cards by sections

- server/routes/reviewsTable.ts
- server/views/pages/reviewsTable.njk
Relates to [dps#2395](https://github.com/ministryofjustice/digital-prison-services/pull/2395)
> INC-1123: Indicate that reviews should be performed by a particular date not on it

- server/data/incentivesApi.test.ts
- server/data/incentivesApi.ts
- server/routes/reviewsTable.test.ts
- server/routes/reviewsTable.ts
- server/testData/incentivesApi.ts
- server/views/pages/reviewsTable.njk
Depends on [incentives-api#373](https://github.com/ministryofjustice/hmpps-incentives-api/pull/373)
> INC-1130: Display "New to prison" flag in reviews table

- server/views/pages/about-national-policy.njk
Wrap the `<a>` element inside a `<p>` element to be sure style is correct.
> INC-1154: Style of link in About national policy page

- server/data/incentivesApi.ts
- server/routes/all.ts
- server/routes/incentiveLevels.ts
- server/routes/prisonIncentiveLevels.ts
- server/views/pages/incentiveLevel.njk
- server/views/pages/incentiveLevels.njk
- server/views/pages/prisonIncentiveLevel.njk
- server/views/pages/prisonIncentiveLevels.njk
Part 1: read-only views for QA-ing incentive level apis
Each route is only accessible locally and in `dev` environment and there is no navigable link to these pages.
> INC-1177: View incentive levels and their per-prison associated information

- assets/scss/application.scss
- server/data/incentivesApi.ts
- server/data/restClient.ts
- server/routes/analyticsRouter.ts
- server/routes/forms/forms.ts
- server/routes/forms/incentiveLevelForm.test.ts
- server/routes/forms/incentiveLevelForm.ts
- server/routes/forms/prisonIncentiveLevelForm.test.ts
- server/routes/forms/prisonIncentiveLevelForm.ts
- server/routes/home.ts
- server/routes/incentiveLevels.ts
- server/routes/prisonIncentiveLevels.ts
- server/views/pages/incentiveLevel.njk
- server/views/pages/incentiveLevelForm.njk
- server/views/pages/incentiveLevels.njk
- server/views/pages/prisonIncentiveLevel.njk
- server/views/pages/prisonIncentiveLevelForm.njk
- server/views/pages/prisonIncentiveLevels.njk
Part 2: write views for QA-ing incentive level apis
Each route is only accessible locally and in `dev` environment and there is no navigable link to these pages.
Modifications require the user to have additional roles.
As with part 1 (#436), there are no unit or integration tests because these are just mockups: proper designs and testing will follow.
> INC-1177: Edit incentive levels and their per-prison associated information

- .editorconfig
- .husky/pre-commit
- renovate.json
> Tidy up config

- server/utils/azureAppInsights.ts
- server/utils/azureAppinsights.test.ts
Copied/adapted from this Use of force PR:
https://github.com/ministryofjustice/use-of-force/pull/599
> INC-1232: Add user info to AppInsights request

- server/views/pages/home.njk
- server/views/pages/prisonIncentiveLevel.njk
- server/views/pages/prisonIncentiveLevels.njk
- server/views/partials/prisonIncentiveLevelEditPartial.njk
~Vist limits~ → Visit allowance
> INC-1230: Indicate that visit orders are allowances and not hard limits

- server/app.ts
- server/config.ts
- server/utils/nunjucksSetup.ts
… and ensure that templates have access to environment & production variables
> Point out that `production` config & template parameter is true in dev, preprod _and_ prod

- server/routes/reviewsTable.test.ts
- server/views/pages/reviewsTable.njk
> INC-1283: Improve accessibility of links within reviews table

- server/routes/reviewsTable.ts
- server/utils/pagination.ts
- server/views/pages/reviewsTable.njk
> INC-1285: Improve pagination accessibility

- integration_tests/e2e/prisonerImages.cy.ts
- server/data/prisonApi.ts
- server/routes/prisonerImages.test.ts
- server/routes/prisonerImages.ts
…but have them cached for less time
> Announce correct mime type for prisoner photos

- .circleci/config.yml
- cypress.config.ts
- package.json
Ref: https://github.com/ministryofjustice/hmpps-non-associations/pull/103
> Copy CI updates from non-associations

- assets/scss/components/_reviews-table.scss
- server/routes/reviewsTable.test.ts
- server/routes/reviewsTable.ts
- server/utils/pagination.test.ts
- server/utils/pagination.ts
- server/views/pages/incentiveLevelCreateForm.njk
- server/views/pages/incentiveLevelEditForm.njk
- server/views/pages/incentiveLevelReorderForm.njk
- server/views/pages/incentiveLevelStatusForm.njk
- server/views/pages/prisonIncentiveLevel.njk
- server/views/pages/prisonIncentiveLevelAddForm.njk
- server/views/pages/prisonIncentiveLevelEditForm.njk
- server/views/pages/prisonIncentiveLevelNextAddForm.njk
- server/views/pages/reviewsTable.njk
Ref: [NON-211](https://github.com/ministryofjustice/hmpps-non-associations/pull/131)
• Use legacy MoJ pagination component instead of GOV.UK one to match rest of DPS
• Use cancel links instead of buttons like GOV.UK recommend
[NON-211]: https://dsdmoj.atlassian.net/browse/NON-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Design tweaks

- server/data/incentivesApi.ts
- server/data/prisonApi.ts
- server/data/restClient.test.ts
- server/data/restClient.ts
… and add PUT & DELETE methods
> Improve REST client by allowing query parameters to be passed for all methods

- server/routes/forms/incentiveLevelCreateForm.ts
- server/routes/forms/incentiveLevelEditForm.ts
- server/routes/incentiveLevels.test.ts
apparently i missed a change to the copy doc… in april 🤭
> Fix error messages to match copy document

- cypress.config.ts
- feature.env
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- integration_tests/e2e/aboutAnalytics.cy.ts
- integration_tests/e2e/aboutNationalPolicy.cy.ts
- integration_tests/e2e/analytics/behaviourEntries.cy.ts
- integration_tests/e2e/analytics/incentiveLevels.cy.ts
- integration_tests/e2e/analytics/pgdRegionSelection.cy.ts
- integration_tests/e2e/analytics/protectedCharacteristics.cy.ts
- integration_tests/e2e/health.cy.ts
- integration_tests/e2e/home.cy.ts
- integration_tests/e2e/incentiveLevels.cy.ts
- integration_tests/e2e/locationSelection.cy.ts
- integration_tests/e2e/login.cy.ts
- integration_tests/e2e/prisonIncentiveLevels.cy.ts
- integration_tests/e2e/prisonerImages.cy.ts
- integration_tests/e2e/reviewsTablePage.cy.ts
- integration_tests/mockApis/auth.ts
- integration_tests/mockApis/manageUsersApi.ts
- integration_tests/plugins/index.ts
- server/config.ts
- server/data/hmppsAuthClient.test.ts
- server/data/hmppsAuthClient.ts
- server/data/manageUsersApiClient.test.ts
- server/data/manageUsersApiClient.ts
- server/index.ts
- server/services/userService.test.ts
- server/services/userService.ts
Cherry picked commit from TS template and tweaked/fixed integration tests.
> INC-1324: Get user and roles from Manage Users API rather than from HMPPS Auth

- .circleci/config.yml
- package-lock.json
- package.json
> INC-1335: Complete upgrade to Node 20.12

- helm_deploy/values-prod.yaml
Ref: [prison-api#2156](https://github.com/ministryofjustice/prison-api/pull/2156)
> INC-1335: Migrate to `prison-api` in Cloud Platform

- .circleci/config.yml
- README.md
Ref [api#579](https://github.com/ministryofjustice/hmpps-incentives-api/pull/579)
> INC-1335: Use latest LTS java for Veracode scanning

- helm_deploy/hmpps-incentives-ui/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Send them to the `#incentives-dev` Slack channel.
> INC-1335: Send alerts to dev channel
